#=jp.dodododo.sql.dialect.Standard
Oracle=jp.dodododo.sql.dialect.Oracle
PostgreSQL=jp.dodododo.sql.dialect.PostgreSQL
HSQL\ Database\ Engine=jp.dodododo.sql.dialect.HSQL
Firebird=jp.dodododo.sql.dialect.Firebird
Microsoft\ SQL\ Server=jp.dodododo.sql.dialect.MSSQLServer
MySQL=jp.dodododo.sql.dialect.MySQL
DB2=jp.dodododo.sql.dialect.DB2
SAP\ DB=jp.dodododo.sql.dialect.MaxDB
Apache\ Derby=jp.dodododo.sql.dialect.Derby
H2=jp.dodododo.sql.dialect.H2
Adaptive\ Server\ Enterprise=jp.dodododo.sql.dialect.Sybase
SQLite=jp.dodododo.sql.dialect.sqlite.SQLite
SQLite3.7.2=jp.dodododo.sql.dialect.sqlite.SQLite3_7_2

